### ISSUE TITLE
Retrieve node name and namespace

### ISSUE THREAD

**Issue by mmcdole** [ChrisTrenkamp/goxpath#1]
I'd like to be able to retrieve a list of nodes and access their name and namespace prefix, not just their value.

For example, I'd like to be able to do something like this:
```
/rss/channel/*
```

```xml
<rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
    <channel>
        <title>This Week in Tech (MP3)</title>
        <itunes:author>TWiT</itunes:author>
        <itunes:subtitle>Some subtitle</itunes:subtitle>
   </channel>
</rss>
```

Then be able to pull out namespace prefix and node name from the our result.
```
result.value = "This Week in Tech (MP3)"
result.ns = ""
result.name = "title"

result.value = "TWiT"
result.ns = "itunes"
result.name = "author"

result.value = "Some subtitle"
result.ns = "itunes"
result.name = "subtitle"
```

I'm not sure if this is possible with the current ```XPRes``` that we get back now or not.

If we had that in place, perhaps it would also be possible to support this XPath 2.0 method to retrieve element name as well:

```
//rss/*/name()
```

Nice work on this library! Really like that it is capable of querying based on namespace (that is something [xmlpath](https://godoc.org/launchpad.net/xmlpath) can't do). I'm currently building an RSS/Atom feed parser on top of it.

**Comment by ChrisTrenkamp** [comment]
Hello.

You can type assert your result for [XMLEle](https://github.com/ChrisTrenkamp/goxpath/blob/master/tree/xmltree/result/xmlele/xmlele.go) and get the name/prefix from the StartElement field.

    package main

    import (
    	"bytes"
    	"encoding/xml"
    	"fmt"

    	"github.com/ChrisTrenkamp/goxpath/goxpath"
    	"github.com/ChrisTrenkamp/goxpath/tree/xmltree"
    	"github.com/ChrisTrenkamp/goxpath/tree/xmltree/result/xmlele"
    )

    const atomfeed = xml.Header + `
        <rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
            <channel>
                <title>This Week in Tech (MP3)</title>
                <itunes:author>TWiT</itunes:author>
                <itunes:subtitle>Some subtitle</itunes:subtitle>
           </channel>
        </rss>
        `

    var tree = xmltree.MustParseXML(bytes.NewBufferString(atomfeed))

    func main() {
    	var xp = goxpath.MustParse(`//rss/*`)
    	res := xmltree.Exec(xp, tree, nil)

    	for _, i := range res {
    		if chEle, ok := i.(*xmlele.XMLEle); ok {
    			fmt.Println("Channel element: ", chEle.StartElement.Name)
    		}
    	}

    	xp = goxpath.MustParse(`//rss/channel/*`)
    	res = xmltree.Exec(xp, tree, nil)

    	for _, i := range res {
    		if chEle, ok := i.(*xmlele.XMLEle); ok {
    			fmt.Println("Child elements: ", chEle.StartElement.Name)
    		}
    	}
    }

Which prints:

    Channel element:  { channel}
    Child elements:  { title}
    Child elements:  {http://www.itunes.com/dtds/podcast-1.0.dtd author}
    Child elements:  {http://www.itunes.com/dtds/podcast-1.0.dtd subtitle}

Also, be sure to pull the latest because I found a bug with wildcard queries against nodes with namespaces, which is fixed now.

**Comment by mmcdole** [comment]
Cheers!  Thanks for the response.  I think that will solve my issue.

**Comment by ChrisTrenkamp** [comment]
local-name(), namespace-uri(), and name() have been added and should be working now.  Just be aware that I'm sticking to the spec, which states for all of these: "The [function] function returns the [name] of the node in the argument node-set that is first in document order."  So these functions will only return one result.

    package main
    
    import (
	    "bytes"
	    "encoding/xml"
	    "fmt"

	    "github.com/ChrisTrenkamp/goxpath/goxpath"
	    "github.com/ChrisTrenkamp/goxpath/tree/xmltree"
    )

    const atomfeed = xml.Header + `
        <rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
            <channel>
                <title>This Week in Tech (MP3)</title>
                <itunes:author>TWiT</itunes:author>
                <itunes:subtitle>Some subtitle</itunes:subtitle>
           </channel>
        </rss>
        `
    
    var tree = xmltree.MustParseXML(bytes.NewBufferString(atomfeed))
    
    func main() {
	    var xp = goxpath.MustParse(`//rss/*/name()`)
	    res := goxpath.MustExec(xp, tree, nil)
	    fmt.Println(res[0])
    }

This will print `channel`.
