### ISSUE TITLE
last() / index after attribute restriction query doesn't parse

### ISSUE THREAD

**Issue by agriic** [ChrisTrenkamp/goxpath#10]
trying to run
<pre>var xmlStr = xml.Header + `&lt;root&gt;
  &lt;text attr="1"&gt;This is some text 1.1.&lt;/text&gt;
  &lt;text attr="1"&gt;This is some text 1.2.&lt;/text&gt;
  &lt;text attr="2"&gt;This is some text. 2.1&lt;/text&gt;
  &lt;text attr="2"&gt;This is some text. 2.2&lt;/text&gt;
  &lt;text attr="2"&gt;This is some text. 2.3&lt;/text&gt;
&lt;/root&gt;`

var xpExec = goxpath.MustParse(`/root/text[@attr="2"][2]`)</pre>

lib throws panic: Malformed XPath expression

this is one of examples at 1.0 spec. And result should be "This is some text. 2.2"

**Comment by ChrisTrenkamp** [comment]
The issue should be resolved now.  Thanks for submitting the issue.

**Comment by agriic** [comment]
Looks like last() isn't working properly.
same xml. path: `/root/text[@attr="2"][last()]` it returns zero results, but should be `<text attr="2">This is some text. 2.3</text>`
As it seems, last() returns 5 not 3 - it has counted results before @attr="2" predicate execution.

**Comment by ChrisTrenkamp** [comment]
The size of the context's were not being updated.  Your example with last() should be working now.

**Comment by agriic** [comment]
Yes. Works as expected. Thanks.
