### ISSUE TITLE
Could it support non-strict html parsing?

### ISSUE THREAD

**Issue by dlintw** [ChrisTrenkamp/goxpath#12]
If will be more useful if it could support non-strict html parsing.
Or, is there any tool could convert bad html into normalized file which could be read by goxpath?

**Comment by ChrisTrenkamp** [comment]
[https://godoc.org/github.com/ChrisTrenkamp/goxpath/tree/xmltree](https://godoc.org/github.com/ChrisTrenkamp/goxpath/tree/xmltree)

You can pass in a ParseSettings function and set the Strict field to false.  xmltree is at the mercy of the encoding/xml package, so if it can't parse out the HTML, then xmltree won't.  If that happens, you'll have to use a tool like tidy to clean up the HTML before passing it in.

**Comment by ChrisTrenkamp** [comment]
Haven't heard a response for a while.  Closing.
