### ISSUE TITLE
ExecNode bug?

### ISSUE THREAD

**Issue by prettymuchbryce** [ChrisTrenkamp/goxpath#14]
I have a simple example here of a program which takes a `NodeSet` containing two "container" `Nodes`, and runs `ExecNode` on them with a query searching for the text of the "title" elements.

However, in both cases it seems to always return a `NodeSet` as if I had run `ExecNode` from the root node. This leads me to believe `ExecNode` is always executing the query on the root instead of the node that was provided.

Is my understanding of the expected behavior correct? and if so – is this a bug?

```go
package main

import (
	"bytes"
	"fmt"

	"github.com/ChrisTrenkamp/goxpath"
	"github.com/ChrisTrenkamp/goxpath/tree"
	"github.com/ChrisTrenkamp/goxpath/tree/xmltree"
)

func main() {
	var page = `
	<html>
		<body>
			<div class="container">
				<span class="title">title1</span>
			</div>
			<div class="container">
				<span class="title">title2</span>
			</div>
		</body>
	</html>
	`

	var root tree.Node
	var buffer = bytes.NewBuffer([]byte(page))
	root, _ = xmltree.ParseXML(buffer, parseSettings)
	xpExec, _ := goxpath.Parse("//div[@class=\"container\"]")
	containers, _ := xpExec.ExecNode(root)
	for _, c := range containers {
		xpExec, _ = goxpath.Parse("//span[@class=\"title\"]/text()")
		title, _ := xpExec.ExecNode(c)
		fmt.Println(title[0].ResValue()) // "title1" in both cases
	}
}

func parseSettings(s *xmltree.ParseOptions) {
	s.Strict = false
}
```

**Comment by ChrisTrenkamp** [comment]
```
package main

import (
	"bytes"
	"fmt"

	"github.com/ChrisTrenkamp/goxpath"
	"github.com/ChrisTrenkamp/goxpath/tree"
	"github.com/ChrisTrenkamp/goxpath/tree/xmltree"
)

func main() {
	var page = `
	<html>
		<body>
			<div class="container">
				<span class="title">title1</span>
			</div>
			<div class="container">
				<span class="title">title2</span>
			</div>
		</body>
	</html>
	`

	var root tree.Node
	var buffer = bytes.NewBuffer([]byte(page))
	root, _ = xmltree.ParseXML(buffer, parseSettings)
	xpExec, _ := goxpath.Parse("//div[@class=\"container\"]")
	containers, _ := xpExec.ExecNode(root)
	for _, c := range containers {
		xpExec, _ = goxpath.Parse("./span/text()")
		title, _ := xpExec.ExecNode(c)
		fmt.Println(title[0].ResValue()) // "title1" in both cases
	}
}

func parseSettings(s *xmltree.ParseOptions) {
	s.Strict = false
}
```

```
title1
title2
```

**Comment by prettymuchbryce** [comment]
Thanks for the clarification. I think that makes sense given the XPath Spec. Consider it a feature request to be able to copy nodes into a new subtree such that it would be possible to execute queries on them as roots.

**Comment by ChrisTrenkamp** [comment]
Sorry, my comment about `text()` was incorrect.  It selects all text nodes under the current context.  It's when you take the string value (`ResValue()`) from a result set is when it only takes the value of the first node.

As for this feature request, can you post an example that can't be resolved by beginning your XPath expressions with `./` or `.//`?
