### ISSUE TITLE
Parser returns wrong tree structure for expressions that begin with functions

### ISSUE THREAD

**Issue by mosopeogundipe** [ChrisTrenkamp/goxpath#19]
The parser isn't behaving correctly when an XPath expression starts with a function. An example expression is **current()/oc-platform:state/oc-platform:type = 'TRANSCEIVER'**, which is available in the public openconfig models [https://github.com/openconfig/public/blob/5897507ecdb54453d4457e7dbb0a3d4b7ead4314/release/models/platform/openconfig-platform-transceiver.yang#L557]() 

I noticed two issues, for which I'm currently testing my fixes but I still want to report them anyway.

1. Whenever an XPATH expression starts with a function, parser would always return an empty root node in the AST tree. This issue occurred even for small expressions like _current()='TRANSCEIVER'_. After fixing this I encountered the second issue. 

2. Whenever an XPATH expression starts with a function and contains more than one node (e.g. the sample openconfig expression mentioned above), parser creates a wrong AST tree structure.

**Comment by ChrisTrenkamp** [comment]
Looks good.  Thanks.
