### ISSUE TITLE
Select root node

### ISSUE THREAD

**Issue by mmcdole** [ChrisTrenkamp/goxpath#2]
I would expect the path ```/*``` to [select the root node](http://stackoverflow.com/a/9497787).  However, it always returns no results for me.

This is useful for if I wish to pull attributes from the root node of an RSS feed which may sometimes be "rss" and in other version be "rdf".

For now I have two paths to cover both cases but it would be cool if I could select the root element via a wildcard.

**Comment by ChrisTrenkamp** [comment]
Can you paste an example?  I can't reproduce this.

The last commit fixed an issue with wildcard queries.  Did you get the latest code?

**Comment by mmcdole** [comment]
@ChrisTrenkamp looks like I was a commit behind on this machine.  Updating to latest seems to fix it.  Thanks!
