### ISSUE TITLE
panic: Malformed XML file

### ISSUE THREAD

**Issue by suntong** [ChrisTrenkamp/goxpath#7]
Hi @ChrisTrenkamp, 

Please take a look at this [simple file that beautify XML](https://github.com/suntong/lang/blob/master/lang/Go/src/xml/gxp_XMLBeautify.go). I.e.,

```go
func main() {

	parseTree := xmltree.MustParseXML(os.Stdin)
	goxpath.Marshal(parseTree, os.Stdout)
}

```

This is how I tested it, and their results:

```
$ echo '<message><org><cn>Some org-or-other</cn><ph>Wouldnt you like to know</ph></org><contact><fn>Pat</fn><ln>Califia</ln></contact></message>' | go run gxp_XMLBeautify.go
panic: Malformed XML file

goroutine 1 [running]:
panic(0x51df40, 0xc420064530)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/ChrisTrenkamp/goxpath/tree/xmltree.MustParseXML(0x5ee540, 0xc420088000, 0x0, 0x0, 0x0, 0x4806ad, 0xc4200001a0)
        /export/repo/go-arch/src/github.com/ChrisTrenkamp/goxpath/tree/xmltree/xmltree.go:39 +0xb0
main.main()
...

$ echo "<root><this><is>a</is><test /></this></root>" | go run gxp_XMLBeautify.go
panic: Malformed XML file

goroutine 1 [running]:
panic(0x51df40, 0xc42000aa10)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/ChrisTrenkamp/goxpath/tree/xmltree.MustParseXML(0x5ee540, 0xc420034008, 0x0, 0x0, 0x0, 0x4806ad, 0xc4200001a0)
        /export/repo/go-arch/src/github.com/ChrisTrenkamp/goxpath/tree/xmltree/xmltree.go:39 +0xb0
main.main()
...
```

how can I make it works? Thanks!

**Comment by ChrisTrenkamp** [comment]
You're missing the XML declaration in your input.  Use [ParseSettings](https://godoc.org/github.com/ChrisTrenkamp/goxpath/tree/xmltree#ParseSettings) to turn off strict validation.

**Comment by suntong** [comment]
Hmm...

- func MustParseXML(r io.Reader, op ...**ParseSettings**) tree.Node
- type ParseSettings _func_(s * **ParseOptions**)
- type **ParseOptions** _struct_ {     Strict  bool } 

Can you show me how to put them together please? Thx.

**Comment by ChrisTrenkamp** [comment]
reader := xmltree.MustParseXML(r, func(s *xmltree.ParseOptions) {
s.Strict = false
})

**Comment by suntong** [comment]
Thanks! :+1: 

Before closing this, let me ask one related question -- here's how it runs:

```
$ echo "<root><this><is>a</is><test /></this></root>" | go run gxp_XMLBeautify.go
<root><this><is>a</is><test></test></this></root>

```

I mean, how come the output is like this, with not indenting, while the same code (from #5) output nicely indented XML?

**Comment by ChrisTrenkamp** [comment]
Whitespace is significant in XML.  Text nodes that is just whitespace is still a text node, but a lot of applications choose to ignore whitespace.  Also, you shouldn't turn off strict validation unless there's a good reason.  You just need to insert the XML declaration in your input.

**Comment by suntong** [comment]
gotya. Thanks!

**Comment by ChrisTrenkamp** [comment]
Also, if you want to beautify your XML, use the encoding/xml package.

**Comment by suntong** [comment]
Oh, I now know. I [thought it was impossible](https://groups.google.com/d/msg/golang-nuts/lHPOHD-8qio/0xQ7xikQAgAJ). :-)
